### ISSUE TITLE
Handle auth error in case of bad credentials

### ISSUE THREAD

**Issue by diimpp** [seaneustace/Bulk-Redirect-CSV-Export#1]
Hi, great tool, a suggestion to increase usability:

If credentials are incorrect, then script will continue like nothing happened
![image](https://github.com/user-attachments/assets/29e1eccf-f605-483c-b3ee-6b0853b470ed)

Received api response at such request looks like
```json
{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```

**Comment by seaneustace** [comment]
Thanks for flagging this, fixed in v2.1
https://github.com/seaneustace/Bulk-Redirect-CSV-Export/releases/tag/v2.1-beta
