### ISSUE TITLE
Use list name as file name for export

### ISSUE THREAD

**Issue by diimpp** [seaneustace/Bulk-Redirect-CSV-Export#2]
Currently it always exports to `results.csv` -- would be cool to export to the file named after list for export.

https://github.com/seaneustace/Bulk-Redirect-CSV-Export/blob/72d68344639abd373630c5c16b0f3592b8265331/csv.sh#L99

**Comment by seaneustace** [comment]
Thanks for flagging this, fixed in v2.1
https://github.com/seaneustace/Bulk-Redirect-CSV-Export/releases/tag/v2.1-beta
